version: "3.0"
services:
  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build: ./app
    depends_on:
      - db
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    command: flask run --host=0.0.0.0 --port=8080
  db:
    build: ./db/mysql
    cap_add:
      - SYS_NICE
    expose:
      - "3306"
    volumes:
      - ./db/mysql/volume:/var/lib/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/init.d:/docker-entrypoint-initdb.d
    env_file:
      - ./.env.dev
