"""empty message

Revision ID: c8dd3426c38f
Revises: beb605960301
Create Date: 2020-10-01 05:36:46.769386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8dd3426c38f'
down_revision = 'beb605960301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('password_hash', sa.String(length=120), nullable=False))
    op.drop_index('certificate_url', table_name='students')
    op.drop_column('students', 'certificate_url')
    op.drop_column('students', 'passowrd')
    op.add_column('workers', sa.Column('password_hash', sa.String(length=120), nullable=False))
    op.add_column('workers', sa.Column('position', sa.String(length=120), nullable=True))
    op.drop_index('certificate_url', table_name='workers')
    op.drop_column('workers', 'certificate_url')
    op.drop_column('workers', 'passowrd')
    op.drop_column('workers', 'postions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('postions', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('workers', sa.Column('passowrd', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('workers', sa.Column('certificate_url', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('certificate_url', 'workers', ['certificate_url'], unique=True)
    op.drop_column('workers', 'position')
    op.drop_column('workers', 'password_hash')
    op.add_column('students', sa.Column('passowrd', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('students', sa.Column('certificate_url', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('certificate_url', 'students', ['certificate_url'], unique=True)
    op.drop_column('students', 'password_hash')
    # ### end Alembic commands ###
