"""empty message

Revision ID: fe518ff2e5a9
Revises: 724492699818
Create Date: 2020-09-30 17:31:42.196763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe518ff2e5a9'
down_revision = '724492699818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('students', 'cupdated_at')
    op.add_column('workers', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('workers', 'cupdated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('cupdated_at', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('workers', 'updated_at')
    op.add_column('students', sa.Column('cupdated_at', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('students', 'updated_at')
    # ### end Alembic commands ###
